import type { CourseContentBlock, CourseSubModule, QuizQuestion } from './courses';

const courseId = 'spice-trade-supply-specialist';

type SpiceProfile = {
  slug: string;
  title: string;
  identity: string;
  origins: string;
  seasonality: string;
  processing: string;
  specifications: string;
  risks: string;
  handling: string;
  sourcing: string;
  specScenario: string;
  specAnswer: string;
  riskScenario: string;
  riskAnswer: string;
  handlingScenario: string;
  handlingAnswer: string;
};

function question(id: string, prompt: string, correctAnswer: string, distractors: [string, string]): QuizQuestion {
  return { id, question: prompt, options: [correctAnswer, ...distractors], correctAnswer };
}

const foundationLessons: CourseSubModule[] = [
  {
    id: `${courseId}-1`, courseId, order: 1,
    title: 'Global Spice Trade Fundamentals',
    description: 'Understand how spices move from farms and collectors through processors, exporters, importers, and industrial or retail buyers.',
    content: [
      { type: 'section', heading: 'The spice value chain', paragraphs: ['Spices may pass through growers, village collectors, aggregators, cleaning or grinding units, sterilization providers, laboratories, exporters, importers, distributors, and manufacturers. An operator must identify who controlled each step and which records preserve traceability.'], bullets: ['Define the exact product: botanical identity, origin, crop year, whole or processed form, intended use, and required treatment.', 'Map custody from farm or aggregation point to the buyer, including subcontracted processing and storage.', 'Treat price as meaningful only after specification, quantity, packing, Incoterm, payment, inspection, and claim terms are aligned.'] },
      { type: 'section', heading: 'Origin, season, and commercial form', paragraphs: ['Harvest calendars affect freshness, availability, moisture risk, and negotiation, but dates vary by variety, altitude, weather, and producing region. Validate the current crop situation with qualified local sources.'], bullets: ['Whole spices usually preserve identity and volatile compounds better than ground product and are easier to inspect visually.', 'Ground spices create additional blending, contamination, authenticity, and cross-contact controls.', 'Steam treatment, irradiation, fumigation, extraction, or other processing must be agreed with the buyer and legally acceptable at destination.'] },
      { type: 'callout', tone: 'key', title: 'Operator rule', text: 'Never source from a product name alone. Build a written specification and traceability requirement before comparing suppliers.' },
      { type: 'callout', tone: 'warning', title: 'Requirements change', text: 'Food law, residue limits, treatment permissions, labeling, and import controls differ by destination and can change. Confirm the current official requirements for every shipment.' },
    ],
    passScore: 2,
    questions: [
      question('q1', 'A buyer asks for “premium spice” without further detail. What should happen first?', 'Define identity, origin, form, use, specification, quantity, packing, and destination requirements', ['Collect prices before asking any technical questions', 'Assume the supplier’s premium grade matches every market']),
      question('q2', 'Why is a custody map important in spice sourcing?', 'It identifies who handled each stage and what evidence supports traceability', ['It guarantees the lowest freight rate', 'It removes the need for sampling and testing']),
      question('q3', 'A treatment is common in the origin country. Can the operator assume the destination accepts it?', 'No; confirm buyer acceptance and current destination rules before supply', ['Yes; origin-country practice controls every destination', 'Yes, provided the spice is shipped whole']),
    ],
  },
  {
    id: `${courseId}-2`, courseId, order: 2,
    title: 'Indian Spice Supply',
    description: 'Map India’s producing regions, aggregation channels, processors, exporters, crop cycles, and quality infrastructure.',
    content: [
      { type: 'section', heading: 'A diverse production system', paragraphs: ['India supplies tropical plantation spices, seed spices, rhizomes, chillies, and specialty products across distinct agro-climatic zones. State and district matter because variety, harvest window, processing practice, logistics, and risk are local.'], bullets: ['Southern and coastal belts are important for products such as pepper, cardamom, cloves, nutmeg, ginger, and turmeric.', 'Western and north-western belts are major sources of cumin, coriander, fennel, fenugreek, mustard, and ajwain.', 'Chilli, turmeric, ginger, mustard, and coriander have multiple important origins; never reduce them to one state or season.'] },
      { type: 'section', heading: 'From mandi to export processor', bullets: ['Clarify whether a seller is a grower group, trader, commission agent, processor, sterilization unit, manufacturer, or exporter.', 'Verify licenses and registrations relevant to the activity, facility controls, subcontractors, lot coding, recall capability, and export experience.', 'Use representative sampling and competent laboratories; a certificate from one lot does not establish the quality of another.'] },
      { type: 'section', heading: 'Indian quality infrastructure', paragraphs: ['Spices Board India operates quality evaluation services for the spice industry and publishes export and quality information. Indian food businesses also need to identify applicable FSSAI requirements, while BIS, AGMARK, Codex, ISO, buyer standards, and destination rules may contribute separate specifications.'], bullets: ['Determine which registrations, export procedures, inspections, or mandatory tests apply to the exact product and destination.', 'Match the laboratory scope and validated method to the required parameter.', 'Keep commercial samples, sealed reference samples, test reports, treatment records, and lot-level traceability linked.'] },
      { type: 'callout', tone: 'warning', title: 'Do not generalize', text: 'India-wide crop dates and compliance checklists are not substitutes for current product-, state-, facility-, and destination-specific verification.' },
    ],
    passScore: 2,
    questions: [
      question('q1', 'Two Indian suppliers offer the same spice from different districts. What is the strongest comparison?', 'Compare variety, crop, processing, traceability, representative samples, tests, capacity, and commercial terms', ['Choose only from the state name', 'Choose the supplier with the shortest product description']),
      question('q2', 'A processor provides a test report for an earlier lot. What should the operator do?', 'Require evidence tied to the offered lot using an appropriate sampling and testing plan', ['Treat the old report as permanent approval', 'Skip testing because the facility is registered']),
      question('q3', 'Which source should determine an export shipment’s exact compliance checks?', 'Current official origin and destination requirements applied to the specific product and shipment', ['A generic checklist copied from another spice', 'The previous year’s buyer conversation alone']),
    ],
  },
  {
    id: `${courseId}-3`, courseId, order: 3,
    title: 'International Spice Supply',
    description: 'Evaluate global origins, import channels, processing hubs, routes, suppliers, and country-specific supply risks.',
    content: [
      { type: 'section', heading: 'Global origin networks', paragraphs: ['International spice supply is multi-origin. Important networks include South and Southeast Asia, China, the Middle East, East Africa, Madagascar and other Indian Ocean origins, Europe, the Caribbean, and the Americas. Production origin, processing country, and exporting country may differ.'], bullets: ['Record country and, where material, region of cultivation—not only the port or trader location.', 'Identify whether goods were blended, ground, treated, repacked, or re-exported in another country.', 'Check seasonal concentration, weather exposure, port dependency, political or sanctions risk, and realistic replenishment time.'] },
      { type: 'section', heading: 'Supplier qualification', bullets: ['Verify legal identity, beneficial and bank details through controlled procedures, facility and food-safety certifications, product scope, recall history, and references.', 'Audit critical controls directly or through a qualified party; certification does not replace product and lot verification.', 'Agree change-notification rules for origin, crop, process, treatment, laboratory, packaging, or subcontractor.'] },
      { type: 'section', heading: 'Import readiness', bullets: ['Confirm admissibility, importer responsibilities, prior notice or certification, customs classification, labeling, treatment declarations, and documentary evidence.', 'Screen applicable sanctions and restricted-party requirements and use qualified specialists where needed.', 'Plan inspection, sampling, rejection, reconditioning, claims, and recall responsibilities before shipment.'] },
      { type: 'callout', tone: 'key', title: 'Origin is evidence', text: 'Ask where the spice was grown, processed, treated, packed, and exported, and retain evidence for each material claim.' },
    ],
    passScore: 2,
    questions: [
      question('q1', 'A trader exports from Country A but the spice was grown and processed elsewhere. What should the operator record?', 'Cultivation, processing, treatment, packing, and export origins with supporting evidence', ['Only the port of loading', 'Only the trader’s office address']),
      question('q2', 'A supplier has a recognized food-safety certificate. Is lot verification still needed?', 'Yes; verify the certification scope and apply the agreed lot controls', ['No; certification proves every future lot', 'No; certificates replace specifications']),
      question('q3', 'What should be agreed before an international spice shipment leaves origin?', 'Import readiness, documents, inspection, sampling, rejection, claim, and recall responsibilities', ['Only the vessel name', 'Only the retail selling price']),
    ],
  },
  {
    id: `${courseId}-4`, courseId, order: 4,
    title: 'Specifications, Testing, Food Safety & Compliance',
    description: 'Build a lot-control plan covering authenticity, contaminants, hygiene, residues, packaging, documents, and destination rules.',
    content: [
      { type: 'section', heading: 'Build the specification', bullets: ['State botanical and common name, origin, crop or production date, form, grade, sensory profile, size, colour, density, moisture, foreign matter, defects, and product-specific marker compounds.', 'Add microbiological, mycotoxin, pesticide-residue, heavy-metal, illegal-dye, allergen, treatment, and authenticity requirements as applicable.', 'Name the sampling plan, test method or standard, laboratory expectations, acceptance rules, and remedy for failure.'] },
      { type: 'section', heading: 'Control hazards, not certificates', paragraphs: ['Codex hygiene guidance for spices and dried aromatic herbs uses preventive controls from primary production through processing, packing, storage, and transport. A certificate of analysis is one control within a broader supplier and food-safety system.'], bullets: ['Evaluate Salmonella and other microbiological hazards based on product, process, intended use, and law.', 'Control moisture and storage conditions to reduce mould and mycotoxin risk.', 'Assess residues, heavy metals, foreign matter, filth, allergens, illegal colours, economically motivated adulteration, and treatment residues using a risk-based plan.'] },
      { type: 'section', heading: 'Packaging and evidence', bullets: ['Use clean, food-grade, product-compatible packaging with agreed barrier properties and tamper evidence.', 'Protect lots from moisture, heat, light, pests, odour transfer, contamination, and cross-contact; record storage and transport conditions.', 'Reconcile invoice, packing list, origin evidence, health or phytosanitary documents where applicable, treatment records, certificate of analysis, lot codes, and labels.'] },
      { type: 'callout', tone: 'warning', title: 'Educational use', text: 'This course is operational training, not legal, regulatory, laboratory, or food-safety advice. Use qualified professionals and the latest official rules for each transaction.' },
    ],
    passScore: 2,
    questions: [
      question('q1', 'A certificate says “quality passed” but does not identify methods, limits, or the shipment lot. What is missing?', 'Lot linkage, defined parameters, acceptance limits, methods, sampling, and competent test evidence', ['A more decorative certificate design', 'The supplier’s social media handle']),
      question('q2', 'What is the best control for spice safety?', 'A preventive, risk-based system from production through shipment, supported by appropriate lot verification', ['Testing finished goods for one parameter only', 'Relying on smell and appearance alone']),
      question('q3', 'A buyer changes the destination country after testing. What should happen?', 'Reassess destination rules, specifications, documents, treatment acceptance, and labeling before shipment', ['Use the original checklist without review', 'Change only the delivery address']),
    ],
  },
];

const spiceProfiles: SpiceProfile[] = [
  {
    slug: 'black-pepper', title: 'Black Pepper',
    identity: 'Piper nigrum dried berries are traded as black, white, green, cracked, ground, and extracted products. Black pepper retains the outer pericarp; white pepper is processed from ripe berries with the outer layer removed.',
    origins: 'India—especially Kerala, Karnataka, and Tamil Nadu—participates alongside major origins such as Vietnam, Brazil, Indonesia, Sri Lanka, Malaysia, and Cambodia.',
    seasonality: 'Harvest timing varies by origin, altitude, and weather. Ask for crop year, harvest region, drying date, and current availability rather than assuming one global season.',
    processing: 'Harvest maturity, threshing, blanching practices, drying, cleaning, grading, sterilization, and grinding influence colour, aroma, microbiology, density, and shelf life.',
    specifications: 'Typical controls include grade or berry size, bulk density, moisture, foreign matter, light berries, mould or insect damage, volatile oil, piperine where required, microbiology, residues, mycotoxins, and treatment status.',
    risks: 'Watch for excess moisture, mould, Salmonella risk, insects, mineral-oil contamination, exhausted or spent material, origin substitution, foreign matter, and dilution in ground pepper.',
    handling: 'Use dry, odour-free, food-grade packs with moisture protection. Keep lots cool and ventilated, segregate treated and untreated material, and preserve crop and origin traceability.',
    sourcing: 'Ask for origin and crop evidence, processing flow, density and defect results, treatment declaration, representative pre-shipment sample, lot-specific report, capacity, and recall traceability.',
    specScenario: 'A buyer wants bold whole pepper with strong yield by volume. Which control is especially useful alongside berry size and defects?', specAnswer: 'Agree a bulk-density requirement and verify it on a representative lot sample',
    riskScenario: 'Ground pepper shows weak pungency despite normal colour. What is the best response?', riskAnswer: 'Investigate identity and possible dilution or exhausted material using suitable compositional and authenticity tests',
    handlingScenario: 'Pepper arrives warm with condensation inside the liner. What should happen?', handlingAnswer: 'Quarantine the lot and assess moisture, mould, microbiology, and fitness before release',
  },
  {
    slug: 'chilli', title: 'Chilli',
    identity: 'Capsicum fruits are traded whole, crushed, powdered, flaked, or as colour and pungency extracts. Varieties differ greatly in heat, colour, size, wall thickness, and intended use.',
    origins: 'Important Indian supply includes Andhra Pradesh, Telangana, Karnataka, Madhya Pradesh, Maharashtra, Rajasthan, and Tamil Nadu; major international origins include China, Mexico, Peru, Spain, Turkey, and several African producers.',
    seasonality: 'Fresh harvest and market arrivals differ by region and variety. Validate crop timing, carryover stock, drying conditions, and colour retention for the offered lot.',
    processing: 'Maturity at picking, sun or controlled drying, stem removal, cleaning, grading, grinding, sterilization, and extraction affect colour, heat, contamination, and stability.',
    specifications: 'Specify variety or performance target, whole or powder form, moisture, colour value where relevant, capsaicinoids or Scoville heat, defects, foreign matter, microbiology, aflatoxins, residues, illegal dyes, and treatment.',
    risks: 'Key risks include aflatoxins, Salmonella, excess pesticide residues, illegal colours such as Sudan dyes, mould, insect damage, foreign matter, colour loss, and undeclared blending.',
    handling: 'Protect from moisture, heat, oxygen, and light to preserve colour and limit mould. Manage airborne dust and cross-contact during grinding and packing.',
    sourcing: 'Match the variety to buyer heat and colour needs; verify farm or aggregation controls, drying surface, toxin and dye testing, pesticide program, cleaning, treatment, and lot traceability.',
    specScenario: 'A sauce buyer needs repeatable heat from batch to batch. What must the contract define?', specAnswer: 'A measurable capsaicinoid or Scoville range, sampling method, and acceptance rule',
    riskScenario: 'A chilli powder has unusually intense red colour. What is the correct response?', riskAnswer: 'Hold the lot and test for prohibited colourants and authenticity using an appropriate method',
    handlingScenario: 'Whole chillies are offered after storage through a humid monsoon. What deserves immediate attention?', handlingAnswer: 'Inspect and test for moisture, mould, insects, aflatoxins, and microbiological condition',
  },
  {
    slug: 'turmeric', title: 'Turmeric',
    identity: 'Curcuma longa rhizomes are traded fresh, dried whole or fingers, bulbs, powder, oleoresin, and curcumin products. Varieties differ in colour, curcuminoids, aroma, and agronomic traits.',
    origins: 'India is a leading producer with significant supply from Telangana, Maharashtra, Karnataka, Tamil Nadu, Andhra Pradesh, Odisha, and north-eastern states; other origins include Myanmar, Indonesia, China, Vietnam, and parts of Africa and Latin America.',
    seasonality: 'Rhizomes are harvested after crop maturity, then cured and dried. Timing varies by planting cycle and region; confirm crop year, curing date, and storage history.',
    processing: 'Cleaning, curing or boiling, drying, polishing, grading, grinding, steam treatment, and extraction determine appearance, load, colour, and marker content.',
    specifications: 'Control botanical identity, form, moisture, curcuminoid or curcumin target where relevant, volatile oil, ash, foreign matter, colour, microbiology, mycotoxins, residues, heavy metals, and prohibited dyes.',
    risks: 'Risks include lead chromate or other undeclared colour enhancement, starch or filler in powder, high lead or other metals, pesticide residues, mould, Salmonella, exhausted material, and origin or variety substitution.',
    handling: 'Keep dry and protected from light and odours. Prevent cross-contact and retain evidence linking whole material, grinding batch, tests, and finished lot.',
    sourcing: 'Ask for variety and origin, curing method, polishing or colouring declaration, marker results, heavy-metal and illegal-dye controls, grinder traceability, treatment, and representative samples.',
    specScenario: 'A nutraceutical buyer requests high-curcumin turmeric. What is insufficient?', specAnswer: 'Selecting by visual colour alone without an agreed curcuminoid method and limit',
    riskScenario: 'Turmeric appears exceptionally bright and heavy. What should the operator prioritize?', riskAnswer: 'Quarantine and investigate undeclared colour treatment and heavy-metal risk with competent testing',
    handlingScenario: 'A supplier changes from whole-rhizome to outsourced grinding. What is required?', handlingAnswer: 'Requalify the process, cross-contact controls, traceability, sampling, and finished-product testing',
  },
  {
    slug: 'cumin', title: 'Cumin',
    identity: 'Cuminum cyminum dried fruits are commonly called seeds and sold whole, ground, roasted, or as oil and oleoresin. Aroma, seed appearance, and cleanliness drive commercial use.',
    origins: 'India—particularly Gujarat and Rajasthan—is a major source; other origins include Turkey, Syria and neighbouring West Asian areas, Iran, Afghanistan, China, and parts of the Mediterranean.',
    seasonality: 'Cumin is generally a cool-season crop in India, but harvest timing and availability vary by origin. Confirm crop year, rainfall exposure, arrival period, and storage duration.',
    processing: 'Threshing, drying, machine cleaning, gravity separation, colour sorting, grinding, and microbial reduction affect purity, volatile oil, and safety.',
    specifications: 'Specify whole or ground form, purity, seed appearance, moisture, foreign matter, damaged or discoloured seeds, volatile oil where needed, microbiology, residues, mycotoxins, and allergen controls.',
    risks: 'Risks include Salmonella, pesticide residues, mould or mycotoxins, insect damage, stones and field matter, admixture with similar seeds, spent material, and undeclared peanut or other allergen cross-contact.',
    handling: 'Use lined food-grade packs, dry storage, pest control, and segregation from allergenic and strong-odour materials. Protect volatile aroma during prolonged or warm storage.',
    sourcing: 'Verify crop and district, cleaning line, optical sorting, allergen program, pesticide controls, microbiological treatment, volatile-oil expectations, sample representativeness, and lot coding.',
    specScenario: 'A buyer will grind cumin and needs high process yield. What should be defined?', specAnswer: 'Purity, foreign matter, damaged seeds, moisture, and cleaning-loss expectations',
    riskScenario: 'Testing finds undeclared peanut fragments in cumin. What is the correct response?', riskAnswer: 'Reject or quarantine the lot and investigate allergen cross-contact and supplier controls',
    handlingScenario: 'Cumin is stored beside strongly aromatic chemicals. What is the main action?', handlingAnswer: 'Segregate immediately and assess odour contamination before any release',
  },
  {
    slug: 'coriander', title: 'Coriander',
    identity: 'Coriandrum sativum dried fruits are traded as whole seeds, splits, powder, essential oil, and oleoresin. Seed size, colour, citrus character, and volatile oil vary by type and origin.',
    origins: 'Indian supply is important in Rajasthan, Madhya Pradesh, Gujarat, and other states; international origins include Morocco, Eastern Europe, Russia and nearby regions, Canada, and parts of the Mediterranean.',
    seasonality: 'Indian coriander is commonly a cool-season crop, while northern origins follow different calendars. Confirm crop year, maturity, drying weather, and warehouse history.',
    processing: 'Threshing, drying, cleaning, grading, splitting, grinding, and treatment influence purity, aroma, microbiology, and stability.',
    specifications: 'Control seed type and form, purity, colour, moisture, foreign matter, damaged or immature seed, volatile oil where relevant, microbiology, residues, mycotoxins, and treatment status.',
    risks: 'Risks include Salmonella, residues, mould, insects, field matter, admixture, loss of volatile oil, musty odour, and contamination during ground-spice processing.',
    handling: 'Store dry, cool, pest-controlled, and away from odours. Use barrier packaging for ground coriander and manage stock age to protect aroma.',
    sourcing: 'Ask for crop and region, seed type, cleaning and grading performance, volatile-oil target, microbiological reduction, pesticide program, retained sample, and lot traceability.',
    specScenario: 'A flavour buyer rejects coriander with weak citrus notes. What should future contracts add?', specAnswer: 'An agreed sensory profile and, where useful, a volatile-oil requirement with sampling rules',
    riskScenario: 'A lot has a musty odour after wet harvest conditions. What should happen?', riskAnswer: 'Quarantine and assess moisture, mould, mycotoxins, and sensory fitness',
    handlingScenario: 'Ground coriander will be stored for a long period. What control is most relevant?', handlingAnswer: 'Use suitable barrier packaging and control heat, oxygen, moisture, and stock age',
  },
  {
    slug: 'cardamom', title: 'Cardamom',
    identity: 'Small green cardamom is Elettaria cardamomum; large or black cardamoms belong to Amomum-related species and have different size, flavour, processing, and uses. Capsules, seeds, powder, oil, and oleoresin are distinct products.',
    origins: 'Small cardamom is supplied by India, Guatemala, Sri Lanka, Tanzania, and others; Indian production is concentrated in the Western Ghats. Large cardamom is associated with India’s north-east, Nepal, Bhutan, and nearby Himalayan areas.',
    seasonality: 'Picking occurs over multiple rounds and varies by elevation and rainfall. Ask for type, crop year, picking period, curing date, and storage age.',
    processing: 'Maturity selection, washing, curing or drying temperature, tail cutting, grading, colour sorting, decortication, grinding, and treatment influence colour, capsule integrity, aroma, and microbiology.',
    specifications: 'Define species and type, capsule size, colour, split or open capsules, immature or shrivelled pods, insect damage, moisture, seeds-to-husk, volatile oil, residues, microbiology, and treatment.',
    risks: 'Risks include species substitution, artificial colouring, pesticide residues, mould, insects, smoke taint or poor curing, loss of green colour, exhausted seeds, and admixture of old crop.',
    handling: 'Protect from humidity, heat, light, and crushing. Use high-barrier packaging where colour and aroma retention matter and avoid long exposure after opening.',
    sourcing: 'Verify species, origin, crop and curing, grade basis, colour-treatment declaration, residue plan, volatile-oil and defect results, sample-to-lot match, and storage conditions.',
    specScenario: 'A buyer asks for “cardamom” without stating type. What is the first clarification?', specAnswer: 'Confirm species or commercial type, form, grade, sensory target, and intended use',
    riskScenario: 'Green capsules show suspiciously uniform vivid colour. What should happen?', riskAnswer: 'Hold the lot and investigate undeclared colouring and authenticity with appropriate checks',
    handlingScenario: 'Premium green cardamom will cross a hot route. What should the plan emphasize?', handlingAnswer: 'High-barrier packing and controlled exposure to heat, humidity, light, and transit time',
  },
  {
    slug: 'cloves', title: 'Cloves',
    identity: 'Cloves are dried unopened flower buds of Syzygium aromaticum, traded whole, ground, as stem material, oil, or oleoresin. Whole buds and stems have different value and composition.',
    origins: 'Major origins include Indonesia, Madagascar, Tanzania and Zanzibar, Comoros, Sri Lanka, and smaller Indian production in southern states.',
    seasonality: 'Harvest timing differs across hemispheres and islands. Confirm crop year, collection period, drying conditions, and whether old and new crops are blended.',
    processing: 'Buds are harvested before opening, separated from stems, dried, cleaned, graded, and sometimes treated. Drying affects colour, mould risk, and essential-oil retention.',
    specifications: 'Specify whole buds, headless cloves, stems and foreign matter limits, moisture, defective or khoker cloves, size, volatile oil or eugenol where needed, microbiology, residues, and treatment.',
    risks: 'Risks include excess stems, exhausted cloves after oil extraction, mould, insects, high moisture, adulteration in powder, pesticide residues, contamination, and loss of volatile oil.',
    handling: 'Store dry and cool in food-grade barrier packs. Prevent crushing and odour transfer, and control ventilation without exposing product to humid air.',
    sourcing: 'Ask for origin and crop, bud-to-stem control, flotation or defect results where used, volatile-oil expectations, drying and storage records, treatment, testing, and retained samples.',
    specScenario: 'A whole-clove buyer is receiving too much low-value material. What should be tightened?', specAnswer: 'Set limits for stems, headless and defective cloves, foreign matter, and moisture',
    riskScenario: 'Cloves have normal shape but unusually weak aroma and oil yield. What should be investigated?', riskAnswer: 'Possible exhausted material, old crop, or poor storage using sensory and compositional checks',
    handlingScenario: 'A clove lot is packed while still warm from drying. What is the concern?', handlingAnswer: 'Condensation and trapped moisture may drive mould, so cool and verify moisture before packing',
  },
  {
    slug: 'cinnamon-cassia', title: 'Cinnamon & Cassia',
    identity: 'Ceylon or true cinnamon, Cinnamomum verum, and cassia types such as C. cassia, C. burmannii, and C. loureiroi differ in bark structure, flavour, coumarin profile, price, and labeling expectations.',
    origins: 'Sri Lanka is central to Ceylon cinnamon; cassia supply is associated with China, Indonesia, Vietnam, and other Asian origins. India produces and trades several cinnamon materials at smaller scale.',
    seasonality: 'Bark harvest depends on plant growth and local rainfall cycles. Confirm species, crop or processing date, grade, origin, and stock age.',
    processing: 'Peeling, scraping, rolling into quills, drying, cutting, grinding, sorting, and treatment create distinct grades and microbial profiles.',
    specifications: 'Define botanical species, origin, quill or broken form, grade, bark thickness, colour, moisture, ash, volatile oil and marker profile where needed, microbiology, residues, and foreign matter.',
    risks: 'The leading authenticity risk is substitution or undeclared mixing between cinnamon and cassia. Also assess mould, insects, heavy metals, residues, added colour, fillers in powder, and destination limits relevant to coumarin exposure.',
    handling: 'Keep dry and protected from crushing, light, pests, and odours. Ground material needs stronger authenticity, cross-contact, and barrier controls.',
    sourcing: 'Require botanical identity and origin evidence, processing grade, marker or authenticity verification where risk warrants, treatment status, buyer-specific coumarin considerations, and traceable samples.',
    specScenario: 'A buyer specifically orders Ceylon cinnamon. What must the operator avoid?', specAnswer: 'Accepting “cinnamon” paperwork without botanical identity, origin, grade, and authenticity controls',
    riskScenario: 'A ground cinnamon offer is far below the normal commercial range. What is the best response?', riskAnswer: 'Increase identity and adulteration due diligence before considering the commercial offer',
    handlingScenario: 'Quills arrive crushed although chemistry is compliant. Which term matters?', handlingAnswer: 'Agree packaging strength, handling, breakage tolerance, and inspection rules for the chosen grade',
  },
  {
    slug: 'ginger', title: 'Ginger',
    identity: 'Zingiber officinale rhizomes are traded fresh, dried whole or slices, powder, crystallized, pickled, as oil, or oleoresin. Fibre, pungency, aroma, colour, and processing suitability differ by variety and maturity.',
    origins: 'India has many producing states including Madhya Pradesh, Karnataka, Assam, Meghalaya, Kerala, and others; major global origins include China, Nigeria, Nepal, Thailand, Peru, and additional tropical producers.',
    seasonality: 'Fresh and dry ginger calendars vary with planting and destination. Confirm harvest maturity, curing or drying date, crop year, and storage conditions.',
    processing: 'Washing, peeling or scraping, slicing, drying, polishing, grinding, and extraction influence cleanliness, fibre, colour, pungency, microbiology, and yield.',
    specifications: 'Define fresh or dried form, variety or use, size, fibre, moisture, cleanliness, defects, volatile oil, gingerols or pungency where relevant, microbiology, residues, mycotoxins, and treatment.',
    risks: 'Risks include mould, Salmonella in dry product, pesticide residues, sulphiting or bleaching where undeclared or noncompliant, foreign matter, exhausted powder, insects, and high fibre or poor drying.',
    handling: 'Fresh ginger needs ventilation and condition management; dried ginger needs moisture barriers and pest control. Keep strong odours and contaminated surfaces away from both.',
    sourcing: 'Ask about variety, maturity, washing water, peeling, drying surface, sulphite or other treatment, fibre and pungency targets, microbiological control, residues, and lot traceability.',
    specScenario: 'An extraction buyer needs high pungent yield. What should be agreed beyond appearance?', specAnswer: 'A suitable gingerol or pungency measure, volatile oil or extractive target, moisture, and sampling method',
    riskScenario: 'Dried ginger is unusually pale. What should be clarified?', riskAnswer: 'Whether bleaching or sulphiting occurred and whether it is declared and acceptable for the destination',
    handlingScenario: 'Fresh ginger is sealed in moisture-impermeable bags while warm. What is the risk?', handlingAnswer: 'Condensation, decay, and mould require an appropriate ventilation and temperature plan',
  },
  {
    slug: 'nutmeg-mace', title: 'Nutmeg & Mace',
    identity: 'Myristica fragrans produces nutmeg seed and the surrounding aril sold as mace. Whole nutmeg, broken pieces, powder, mace blades, oil, and oleoresin have different grades and authenticity risks.',
    origins: 'Indonesia and Grenada are major international origins, with India, Sri Lanka, and other tropical areas also supplying.',
    seasonality: 'Trees may yield across extended periods with local peaks. Confirm collection period, drying date, crop year, and storage age.',
    processing: 'Fruit opening, aril separation, staged drying, shell cracking, kernel grading, grinding, and treatment determine moisture, mould risk, colour, and aroma.',
    specifications: 'Control product identity, whole or broken grade, sound kernels or blades, moisture, mould and insect damage, volatile oil where needed, mycotoxins, microbiology, residues, foreign matter, and treatment.',
    risks: 'Nutmeg and mace can face aflatoxin and ochratoxin risk, mould, insects, hollow or defective kernels, exhausted material, powder adulteration, species substitution, and poor drying.',
    handling: 'Dry thoroughly before packing; use moisture-protective, pest-resistant packs and cool storage. Segregate rejected mouldy material to prevent blending back.',
    sourcing: 'Verify botanical identity, origin, drying and sorting, defective-kernel controls, mycotoxin sampling plan, volatile-oil needs, treatment, test report linkage, and retained samples.',
    specScenario: 'A shipment contains many light or hollow nutmegs. What contract control helps?', specAnswer: 'Define sound-kernel and defect limits with a representative sampling and inspection method',
    riskScenario: 'Only a small top sample is tested for aflatoxin. Why is this weak?', riskAnswer: 'Mycotoxins can be unevenly distributed, so the lot needs a defensible representative sampling plan',
    handlingScenario: 'Mace is packed before drying is complete. What is the likely consequence?', handlingAnswer: 'Trapped moisture can drive mould and mycotoxin risk, requiring hold and assessment',
  },
  {
    slug: 'fennel', title: 'Fennel',
    identity: 'Foeniculum vulgare dried fruits are traded whole, split, ground, as oil, and in sweet or bitter types. Seed size, green colour, sweetness, anethole character, and intended use affect value.',
    origins: 'India—especially Gujarat and Rajasthan—is important, with supply also from Turkey, Egypt, China, Europe, and Mediterranean regions.',
    seasonality: 'Harvest calendars vary; colour can deteriorate with delayed harvest or storage. Confirm crop year, harvest maturity, drying, and warehouse age.',
    processing: 'Threshing, drying, cleaning, colour and size grading, grinding, and treatment influence purity, appearance, volatile oil, and microbiology.',
    specifications: 'Define type, size and colour grade, moisture, purity, foreign matter, damaged seeds, volatile oil or anethole where relevant, microbiology, residues, and treatment.',
    risks: 'Risks include admixture with similar seeds, spent material, colour deterioration, insects, pesticide residues, Salmonella, mould, foreign matter, and undeclared colouring.',
    handling: 'Protect green grades from light, heat, oxygen, and moisture. Use clean, odour-free packs and pest-controlled storage.',
    sourcing: 'Ask for type and use, crop and origin, colour-grade method, cleaning results, volatile-oil expectation, pesticide and microbiological controls, treatment, and sample retention.',
    specScenario: 'A confectionery buyer values sweet aroma and green appearance. What should be specified?', specAnswer: 'Commercial type, sensory profile, colour and size grade, volatile-oil expectation, and storage age',
    riskScenario: 'A fennel lot includes many visually similar non-fennel seeds. What should happen?', riskAnswer: 'Hold the lot and verify botanical purity and cleaning controls',
    handlingScenario: 'Green fennel will sit in a bright, hot warehouse. What is likely?', handlingAnswer: 'Colour and volatile aroma may deteriorate, so use cool, dark, protective storage',
  },
  {
    slug: 'fenugreek', title: 'Fenugreek',
    identity: 'Trigonella foenum-graecum seeds are traded whole, ground, roasted, germinated, as leaves, or extracts. This lesson focuses on seed spice trade.',
    origins: 'India—particularly Rajasthan, Gujarat, Madhya Pradesh, and nearby belts—is a major source; other origins include Egypt, Turkey, Ethiopia, and parts of the Mediterranean and West Asia.',
    seasonality: 'Indian seed is commonly harvested from a cool-season crop. Confirm crop year, maturity, drying, carryover stock, and storage history.',
    processing: 'Threshing, drying, cleaning, grading, roasting, grinding, and treatment affect bitterness, aroma, colour, microbiology, and purity.',
    specifications: 'Specify whole or ground form, colour, purity, moisture, foreign matter, damaged seed, sensory profile, microbiology, residues, mycotoxins where risk indicates, and treatment.',
    risks: 'Risks include foreign seeds and field matter, pesticide residues, Salmonella, mould, insects, filler in powder, old or rancid material, and allergen cross-contact in shared facilities.',
    handling: 'Use dry, pest-controlled storage and moisture-protective packs. Ground and roasted forms need stronger oxygen and shelf-life controls.',
    sourcing: 'Verify crop and origin, cleaning performance, roast or treatment status, allergen program, pesticide and microbiological controls, sensory approval, lot code, and representative sample.',
    specScenario: 'A buyer needs fenugreek for roasting and milling. What matters beyond seed price?', specAnswer: 'Purity, moisture, damaged seed, sensory quality, cleaning loss, and microbiological condition',
    riskScenario: 'Fenugreek powder contains inconsistent pale particles. What is the response?', riskAnswer: 'Investigate filler or foreign-seed adulteration with identity and compositional controls',
    handlingScenario: 'Roasted fenugreek develops stale notes quickly. What should change?', handlingAnswer: 'Review oxygen barrier, heat exposure, pack size, and declared shelf life',
  },
  {
    slug: 'mustard', title: 'Mustard',
    identity: 'Yellow, brown, and black mustard seeds come from different Brassica or Sinapis species and vary in size, colour, pungency chemistry, oil, and use. Whole seed, powder, flour, oil, and prepared mustard are distinct.',
    origins: 'India, Canada, Nepal, Ukraine and Eastern Europe, Russia and nearby regions, and parts of Europe are important supply areas depending on species and grade.',
    seasonality: 'Northern-hemisphere harvests vary by region. Confirm species, crop year, harvest weather, drying, and storage duration.',
    processing: 'Threshing, drying, cleaning, grading, dehulling, milling, oil extraction, heat treatment, and blending affect purity, enzyme activity, pungency, and safety.',
    specifications: 'Define species or type, colour, size, purity, moisture, foreign matter, damaged seeds, oil or glucosinolate-related performance where relevant, microbiology, residues, and treatment.',
    risks: 'Risks include species substitution, admixture, pesticide residues, mould, insects, foreign matter, loss of functional pungency through heat or storage, and undeclared cross-contact. Mustard itself is a regulated allergen in some markets.',
    handling: 'Segregate and label to manage allergen risk. Store dry and cool; control cleaning, dust, rework, and changeovers in shared facilities.',
    sourcing: 'Confirm species, origin, crop, intended functionality, allergen controls, cleaning purity, heat history, residues, microbiology, traceability, and destination labeling needs.',
    specScenario: 'A condiment maker needs predictable pungency. What should the operator confirm?', specAnswer: 'Mustard species, functional performance, heat history, storage, and a buyer-approved sample',
    riskScenario: 'Mustard is packed on a shared line for a market treating it as an allergen. What is required?', riskAnswer: 'Validated cross-contact controls, traceability, and compliant declaration for the destination',
    handlingScenario: 'Seed was exposed to high heat before milling. What may change?', handlingAnswer: 'Enzyme activity and pungency performance may fall, so revalidate against the intended use',
  },
  {
    slug: 'ajwain', title: 'Ajwain',
    identity: 'Trachyspermum ammi dried fruits are traded whole, ground, and as essential oil. They are valued for a strong thymol-rich aroma and must not be confused with visually similar seeds.',
    origins: 'India is a principal source, including Rajasthan, Gujarat, Madhya Pradesh, and other dry regions; supply also comes from Iran, Afghanistan, Pakistan, Egypt, and neighbouring areas.',
    seasonality: 'Harvest timing varies by producing belt. Confirm crop year, maturity, drying, and whether the lot contains carryover material.',
    processing: 'Threshing, drying, cleaning, grading, grinding, distillation, and treatment affect purity, volatile oil, microbial load, and aroma.',
    specifications: 'Control botanical identity, purity, moisture, foreign matter, damaged seed, sensory strength, volatile oil or thymol where relevant, microbiology, residues, and treatment.',
    risks: 'Risks include substitution with similar-looking seeds, exhausted material after oil removal, field matter, insects, mould, pesticide residues, Salmonella, and dilution in powder.',
    handling: 'Use dry, sealed, odour-protective packs in cool pest-controlled storage. Limit exposure after milling to retain volatile character.',
    sourcing: 'Ask for botanical identity, crop and district, cleaning, volatile-oil expectations, pesticide program, microbiological treatment, authenticity controls, sample linkage, and traceability.',
    specScenario: 'An ajwain lot looks correct but has weak thymol aroma. What should be checked?', specAnswer: 'Crop age, storage, volatile-oil performance, and possible exhausted or substituted material',
    riskScenario: 'A supplier cannot distinguish ajwain from similar seeds in its intake controls. What should happen?', riskAnswer: 'Do not approve until botanical identification and segregation controls are demonstrated',
    handlingScenario: 'Ground ajwain is repeatedly opened in a warm room. What is the concern?', handlingAnswer: 'Volatile aroma loss requires smaller protective packs and controlled exposure',
  },
  {
    slug: 'asafoetida', title: 'Asafoetida',
    identity: 'Asafoetida is oleo-gum-resin obtained from Ferula species and traded as tears, mass, paste, powder, or compounded product. Compounded asafoetida intentionally includes carriers, which must be specified and declared.',
    origins: 'Raw resin traditionally originates in Afghanistan, Iran, and Central Asian regions, while India is a major processor, compounder, consumer, and trading hub.',
    seasonality: 'Collection is tied to plant maturity and tapping cycles rather than a simple annual grain harvest. Confirm collection period, resin age, storage, and processing date.',
    processing: 'Cleaning, ageing, blending, grinding, compounding with permitted carriers, and packing determine strength, consistency, allergen status, and authenticity.',
    specifications: 'Define raw or compounded form, Ferula identity where required, resin proportion or strength, moisture, ash, volatile oil or sulphur-character performance, carrier composition, additives, allergens, contaminants, microbiology, and packaging.',
    risks: 'High-value resin is vulnerable to dilution, undeclared fillers, nonconforming carriers, species substitution, artificial enhancement, contamination, and undeclared wheat or other allergenic ingredients in compounds.',
    handling: 'Use very high odour-barrier packs, strict segregation, and dedicated or well-controlled equipment. Protect from moisture and prevent odour migration to other foods.',
    sourcing: 'Require a full formulation and allergen declaration, raw-resin origin, identity and strength controls, carrier approval, batch consistency, contaminant testing, traceability, and sealed reference samples.',
    specScenario: 'A buyer orders compounded asafoetida. What information is essential?', specAnswer: 'Resin content or strength, every carrier and additive, allergen status, identity, and batch specification',
    riskScenario: 'A powder is sold as pure resin but contains starch. What is the issue?', riskAnswer: 'It is an authenticity and declaration failure requiring quarantine and investigation',
    handlingScenario: 'Asafoetida is stored beside delicate tea. What control failed?', handlingAnswer: 'Odour segregation and high-barrier containment were inadequate',
  },
  {
    slug: 'saffron', title: 'Saffron',
    identity: 'Saffron consists of dried stigmas of Crocus sativus and is traded as threads, cut material, powder, or extracts. Colouring strength, aroma, bitterness, floral-part content, and authenticity define grade.',
    origins: 'Important origins include Iran, India—especially Kashmir—Afghanistan, Spain, Greece, Morocco, and other limited-production regions.',
    seasonality: 'Flowers are harvested during a short local season and stigmas require rapid separation and controlled drying. Confirm harvest year, origin, drying, and storage age.',
    processing: 'Hand picking, stigma separation, drying, conditioning, grading, and packing strongly influence crocin-related colour, picrocrocin-related taste, safranal-related aroma, moisture, and stability.',
    specifications: 'Define thread or powder form, origin claim, floral-part limits, moisture, foreign matter, sensory character, ISO 3632 or other agreed analytical classification where appropriate, microbiology, residues, and packaging.',
    risks: 'Saffron is highly vulnerable to added plant fibres, dyed material, excess style content, moisture weighting, synthetic colour, exhausted material, false origin claims, and dilution in powder.',
    handling: 'Use tamper-evident, light- and moisture-protective small packs with strict inventory control. Preserve chain of custody and sealed references.',
    sourcing: 'Verify grower or processor chain, origin evidence, harvest year, floral morphology, category test results, dye and authenticity controls, pack integrity, mass balance, and retained samples.',
    specScenario: 'A supplier offers premium saffron based only on deep red appearance. What is missing?', specAnswer: 'Identity, floral-part inspection, origin evidence, moisture, and agreed analytical and sensory grading',
    riskScenario: 'Saffron threads release bright colour instantly in cold water. What should the operator consider?', riskAnswer: 'Possible added dye or manipulated material requiring controlled authenticity testing',
    handlingScenario: 'High-value saffron is shipped in an unsealed clear bulk bag. What should change?', handlingAnswer: 'Use tamper-evident light- and moisture-barrier packs with controlled chain of custody',
  },
  {
    slug: 'star-anise', title: 'Star Anise',
    identity: 'Culinary star anise is Illicium verum dried fruit. Correct botanical identification is critical because other Illicium species may be unsuitable or toxic.',
    origins: 'China and Vietnam dominate commercial supply, with smaller regional production elsewhere in East and Southeast Asia.',
    seasonality: 'Harvest peaks vary by area and multiple collections may occur. Confirm crop, drying date, broken-to-whole ratio, and storage age.',
    processing: 'Harvesting, drying, cleaning, grading, breaking, grinding, steam treatment, and oil extraction affect appearance, anethole-rich aroma, safety, and purity.',
    specifications: 'Define Illicium verum identity, whole or broken grade, fruit completeness, moisture, foreign matter, damaged pieces, volatile oil or anethole where needed, microbiology, residues, and treatment.',
    risks: 'The critical risk is admixture with non-culinary Illicium species. Also assess mould, insects, exhausted material, Salmonella, pesticide residues, foreign matter, and powder adulteration.',
    handling: 'Keep dry and protected from crushing, odours, pests, and volatile-oil loss. Ground product needs heightened identity and traceability controls.',
    sourcing: 'Require botanical verification, origin and crop, visual and analytical authenticity controls where warranted, grading, treatment, microbiology, residues, lot traceability, and reference samples.',
    specScenario: 'A buyer orders whole star anise for visible garnish. What belongs in the grade?', specAnswer: 'Botanical identity, whole-fruit completeness, broken and defective limits, moisture, and cleanliness',
    riskScenario: 'A lot contains unfamiliar star-shaped fruits. What is the correct action?', riskAnswer: 'Quarantine and obtain competent botanical or analytical identification before use',
    handlingScenario: 'Star anise powder has no link to its whole-fruit intake lot. What failed?', handlingAnswer: 'Traceability and identity control through grinding failed',
  },
  {
    slug: 'paprika', title: 'Paprika',
    identity: 'Paprika is produced from selected non-pungent or mildly pungent Capsicum fruits and traded as powder, flakes, oleoresin, and colour-standardized ingredients. Colour, flavour, and heat depend on cultivar and process.',
    origins: 'Major supply networks include China, Spain, Peru, Hungary and neighbouring European regions, the United States, and other Capsicum-producing countries, including India for relevant products.',
    seasonality: 'Harvest and drying schedules differ by origin. Confirm crop year, field maturity, drying conditions, storage age, and colour retention.',
    processing: 'Destemming, seed adjustment, drying, milling, blending, sterilization, and extraction influence colour value, heat, flavour, microbiology, and stability.',
    specifications: 'Define colour value by an agreed method, pungency limit, moisture, particle size, defects, foreign matter, microbiology, mycotoxins, residues, prohibited dyes, authenticity, and treatment.',
    risks: 'Risks include aflatoxins, Salmonella, pesticide residues, Sudan or other illegal dyes, undeclared colour adjustment, adulteration, excess heat, oxidation, colour fade, and foreign matter.',
    handling: 'Use oxygen-, light-, and moisture-barrier packs, cool storage, and controlled headspace or pack format where needed. Minimize warm storage to preserve pigments.',
    sourcing: 'Match colour and heat performance to use; verify cultivar or blend, drying, colour method, toxin and dye program, residues, treatment, stability data, sample equivalence, and lot testing.',
    specScenario: 'A sausage buyer needs consistent red colour without added dye. What should be contracted?', specAnswer: 'An agreed extractable-colour range, dye prohibition, heat range, method, and lot acceptance plan',
    riskScenario: 'Paprika colour is exceptionally strong but traceability is weak. What should happen?', riskAnswer: 'Hold and test for authenticity and prohibited dyes before relying on the colour result',
    handlingScenario: 'Paprika is stored in transparent packs near heat. What is likely?', handlingAnswer: 'Oxidation and light exposure may fade colour, requiring barrier packing and cooler storage',
  },
  {
    slug: 'allspice', title: 'Allspice',
    identity: 'Allspice is the dried unripe berry of Pimenta dioica, sold whole, ground, as oil, or oleoresin. Its clove-cinnamon-nutmeg sensory character does not mean it is a blend.',
    origins: 'Jamaica is a premium-recognized origin, with production also in Mexico, Honduras, Guatemala, and other Caribbean and Central American areas.',
    seasonality: 'Berries are harvested green before ripening and dried. Confirm crop year, maturity, drying, origin, and storage age.',
    processing: 'Harvest selection, drying, cleaning, grading, grinding, and treatment affect berry colour, eugenol-rich aroma, mould risk, and microbiology.',
    specifications: 'Define botanical identity, origin if claimed, berry size and colour, moisture, foreign matter, damaged or immature material, volatile oil where relevant, microbiology, residues, and treatment.',
    risks: 'Risks include origin misrepresentation, exhausted material, substitution in powder, mould, insects, Salmonella, excess moisture, residues, and admixture.',
    handling: 'Store cool and dry in odour- and moisture-protective packs. Whole berries protect aroma better; ground product needs tighter shelf-life control.',
    sourcing: 'Ask for botanical and origin evidence, crop and drying, grade, volatile-oil expectation, treatment, microbiology, residues, mass balance for origin claims, and retained samples.',
    specScenario: 'A customer requests Jamaican-origin allspice. What is needed beyond the invoice wording?', specAnswer: 'Traceable origin evidence, lot identity, supplier mass balance, and an agreed grade',
    riskScenario: 'Ground allspice tastes weak and one-dimensional. What should be investigated?', riskAnswer: 'Age, volatile-oil loss, exhausted material, substitution, or dilution',
    handlingScenario: 'The buyer can choose whole berries or pre-ground stock for long storage. Which is safer for aroma?', handlingAnswer: 'Whole berries with suitable dry barrier storage generally retain identity and aroma better',
  },
  {
    slug: 'vanilla', title: 'Vanilla',
    identity: 'Commercial vanilla comes mainly from Vanilla planifolia, with V. tahitensis and other types serving distinct markets. It is traded as cured beans, cuts, powder, extract, oleoresin, and flavour preparations.',
    origins: 'Madagascar is a major source, with supply also from Indonesia, Papua New Guinea, Uganda, India, Mexico, Tahiti and French Polynesia, and other tropical origins.',
    seasonality: 'Beans are harvested after months of development and then cured over weeks or months. Confirm species, flowering or harvest cycle, curing year, and storage condition.',
    processing: 'Blanching or killing, sweating, drying, conditioning, grading, extraction, and blending create aroma and determine moisture, flexibility, vanillin profile, mould risk, and shelf life.',
    specifications: 'Define species, origin claim, bean grade and length, moisture or pliability target, appearance, defects, mould, aroma, vanillin or extract performance where appropriate, microbiology, residues, and extraction basis.',
    risks: 'Risks include false origin or species claims, synthetic vanillin presented as natural vanilla, exhausted beans, moisture manipulation, mould, poor curing, theft or chain-of-custody loss, and adulterated extracts.',
    handling: 'Use secure, food-grade, aroma-barrier packs at appropriate stable conditions; avoid both excessive drying and condensation. Inspect regularly for mould and preserve lot security.',
    sourcing: 'Verify species, origin chain, harvest and curing, grade, moisture basis, authenticity of natural claims, extraction inputs, supplier mass balance, security, representative sample, and lot-specific evidence.',
    specScenario: 'A buyer needs natural vanilla extract with a specific origin claim. What must be verified?', specAnswer: 'Species, bean origin and mass balance, extraction inputs, natural-status rules, and lot traceability',
    riskScenario: 'Vanilla beans are unusually heavy and wet. What should the operator check?', riskAnswer: 'Moisture manipulation, mould risk, net dry value, curing quality, and contract moisture basis',
    handlingScenario: 'Cold beans are moved directly into warm humid air. What is the concern?', handlingAnswer: 'Condensation may promote mould, so acclimatize and manage temperature and humidity',
  },
];

function buildSpiceLesson(profile: SpiceProfile, index: number): CourseSubModule {
  const content: CourseContentBlock[] = [
    { type: 'section', heading: 'Identity, forms, and uses', paragraphs: [profile.identity] },
    { type: 'section', heading: 'Origins and seasons', paragraphs: [profile.origins, profile.seasonality] },
    { type: 'section', heading: 'Processing and buyer specifications', paragraphs: [profile.processing], bullets: [profile.specifications] },
    { type: 'section', heading: 'Quality, safety, and authenticity risks', bullets: [profile.risks] },
    { type: 'section', heading: 'Packaging, storage, and sourcing controls', paragraphs: [profile.handling], bullets: [profile.sourcing] },
    { type: 'callout', tone: 'key', title: 'Buyer-ready check', text: 'Translate the buyer’s intended use into measurable lot requirements, then connect the approved sample, contract, test evidence, packaging, and shipment to the same traceable lot.' },
    { type: 'callout', tone: 'warning', title: 'Verify the destination', text: 'Standards, maximum limits, permitted treatments, allergen rules, labels, and documents vary. Confirm current official and buyer requirements before contracting or shipping.' },
  ];

  return {
    id: `${courseId}-${index + 5}`,
    courseId,
    order: index + 5,
    title: profile.title,
    description: `Evaluate ${profile.title.toLowerCase()} identity, origins, processing, specifications, risks, handling, and sourcing decisions.`,
    content,
    passScore: 2,
    questions: [
      question('q1', profile.specScenario, profile.specAnswer, ['Approve the lot from photographs alone', 'Use the supplier’s generic grade without buyer acceptance criteria']),
      question('q2', profile.riskScenario, profile.riskAnswer, ['Release the lot because the invoice description is correct', 'Blend the lot with stronger material without investigation']),
      question('q3', profile.handlingScenario, profile.handlingAnswer, ['Ignore the condition if the outer bags are intact', 'Change the country-of-origin statement to solve the issue']),
    ],
  };
}

export const SPICE_TRADE_SUPPLY_LESSONS: CourseSubModule[] = [
  ...foundationLessons,
  ...spiceProfiles.map(buildSpiceLesson),
];
